// (◕⁠‿⁠◕⁠ ⁠)~
//YOOO!! ammar is here 
int L1 = 2;
int L2 = 3;
int L3 = 4;
int L4 = 5;
int L5 = 6;
int L6 = 7;
int L7 = 8;
String yoo = "mario aa";
int i=0;
int tt=70;
int t;
int l=7.1;
void setup() {
  pinMode(L1, OUTPUT);
  pinMode(L2, OUTPUT);
  pinMode(L3, OUTPUT);
  pinMode(L4, OUTPUT);
  pinMode(L5, OUTPUT);
  pinMode(L6, OUTPUT);
  pinMode(L7, OUTPUT);
  Serial.begin(9600);
}

void loop() {
  t=tt;  
   for (int i = 0; i < yoo.length(); i++) {
  if (yoo[i]=='y'&&t>0) {y (l); t= t-l; }
  if (yoo[i]=='o'&&t>0){o (l); t= t-l; }
  if (yoo[i]=='a'&&t>0){a (l); t= t-l; }
  if (yoo[i]=='m'&&t>0){m (l); t= t-l; }
   if (yoo[i]=='r'&&t>0){r (l); t= t-l; }
   if (yoo[i]=='b'&&t>0){b(l); t= t-l; }
   if (yoo[i]==' '&&t>0){esp(l); t= t-l; }
     if (yoo[i]=='i'&&t>0){I(l); t= t-l; }
   } 
      if(t>0){
    digitalWrite(L1, HIGH);
    digitalWrite(L2, LOW);
    digitalWrite(L2, LOW);
    digitalWrite(L3, LOW);
    digitalWrite(L4, LOW);
    digitalWrite(L5, LOW);
    digitalWrite(L6, LOW);
    digitalWrite(L7, HIGH);
    delay(t);}
  
}
int y(int d) {
  digitalWrite(L1, HIGH); //////////////////////////////////////////////////////////////////////////////////y
    digitalWrite(L2, 1);
    digitalWrite(L3, 1);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L3, HIGH);
    digitalWrite(L4, HIGH);
    digitalWrite(L5, HIGH);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, 1);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, 1);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);
}
int o(int d){              ///////////////////////////////////////////////////////////////////////////////////////////////o
digitalWrite(L1, HIGH);   
    digitalWrite(L2, HIGH);
    digitalWrite(L3, HIGH);
    digitalWrite(L4, HIGH);
    digitalWrite(L5, HIGH);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L3, 1);
    digitalWrite(L4, 1);
    digitalWrite(L5, 1);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/5);
            digitalWrite(L1, 1);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, 1);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);}
    
    int m(int d){              ///////////////////////////////////////////////////////////////////////////////////////////////m
digitalWrite(L1, HIGH);   
    digitalWrite(L2, HIGH);
    digitalWrite(L3, HIGH);
    digitalWrite(L4, HIGH);
    digitalWrite(L5, HIGH);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/7);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 1);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/7);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/7);
            digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/7);
     digitalWrite(L1, 1);
    digitalWrite(L2, 0);
    digitalWrite(L3, 1);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, 1);
    delay(d/7);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 1);
    digitalWrite(L3, 1);
    digitalWrite(L4, 1);
    digitalWrite(L5, 1);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/7);
            digitalWrite(L1, 1);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, 1);
    delay(d/7);}
    int r(int d){              ///////////////////////////////////////////////////////////////////////////////////////////////r
digitalWrite(L1, HIGH);   
    digitalWrite(L2, HIGH);
    digitalWrite(L3, HIGH);
    digitalWrite(L4, HIGH);
    digitalWrite(L5, HIGH);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L2, 1);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);
            digitalWrite(L1, 1);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, 1);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);}
    int a(int d) {
  digitalWrite(L1, HIGH); //////////////////////////////////////////////////////////////////////////////////a
    digitalWrite(L2, 1);
    digitalWrite(L3, 1);
    digitalWrite(L4, 1);
    digitalWrite(L5, 1);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/6);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 1);
    digitalWrite(L3, 0);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/6);
            digitalWrite(L1, HIGH);
    digitalWrite(L2, 1);
    digitalWrite(L3, 0);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/6);       
        digitalWrite(L1, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L3, HIGH);
    digitalWrite(L4, HIGH);
    digitalWrite(L5, HIGH);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/6);
        digitalWrite(L1, 1);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, 1);
    delay(d/6);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/6);
}
int b(int d){              ///////////////////////////////////////////////////////////////////////////////////////////////b
digitalWrite(L1, HIGH);   
    digitalWrite(L2, HIGH);
    digitalWrite(L3, HIGH);
    digitalWrite(L4, HIGH);
    digitalWrite(L5, HIGH);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/6);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 1);
    digitalWrite(L3, 0);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/6);
    digitalWrite(L1, HIGH);
    digitalWrite(L2, 1);
    digitalWrite(L3, 1);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/6);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 1);
    digitalWrite(L5, 0);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/6);
            digitalWrite(L1, 1);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 1);
    digitalWrite(L5, 1);
    digitalWrite(L6, 1);
    digitalWrite(L7, 1);
    delay(d/6);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/6);}
    int esp(int d){              ///////////////////////////////////////////////////////////////////////////////////////////////____
digitalWrite(L1, HIGH);   
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);
            digitalWrite(L1, 1);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, 1);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, 0);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 0);
    digitalWrite(L7, HIGH);
    delay(d/5);}
    int I(int d){              ///////////////////////////////////////////////////////////////////////////////////////////////i
digitalWrite(L1, HIGH);   
    digitalWrite(L2, 1);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/5);
 digitalWrite(L1, HIGH);   
    digitalWrite(L2, 1);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/5);
        digitalWrite(L1, HIGH);
    digitalWrite(L2, HIGH);
    digitalWrite(L3, 1);
    digitalWrite(L4, 1);
    digitalWrite(L5, 1);
    digitalWrite(L6, HIGH);
    digitalWrite(L7, HIGH);
    delay(d/5);
    digitalWrite(L1, HIGH);   
    digitalWrite(L2, 1);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/5);
     digitalWrite(L1, HIGH);   
    digitalWrite(L2, 1);
    digitalWrite(L3, 0);
    digitalWrite(L4, 0);
    digitalWrite(L5, 0);
    digitalWrite(L6, 1);
    digitalWrite(L7, HIGH);
    delay(d/5);}
